name: FoxBukkit
main: com.foxelbox.foxbukkit.core.FoxBukkit
version: 1.0.0
depend: [WorldEdit, FoxBukkitChatComponent]
softdepend: [LogBlock]
commands:
  fb:
    description: Runs any FoxBukkit command (used for console)
    permission: foxbukkit.no_one_has_this_ever
    usage: /<command>
  fbluareload:
    description: Reloads the FB Lua engine
    permission: foxbukkit.luareload
    usage: /<command>